name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    # Install dependencies
    - name: Install FLTK and PortAudio
      run: |
        sudo apt-get update
        sudo apt-get install -y libfltk1.3-dev portaudio19-dev pkg-config

    # Run configure.sh script
    - name: Run configure script
      run: |
        ${PWD}/.github/workflows/configure.sh

    - name: Build with Make
      run: make

    - name: Run tests
      run: make check

    - name: Make distcheck
      run: make distcheck
