name: CMake with vcpkg (GCC only)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc]
        cpp_compiler: [g++]

      fail-fast: true

    steps:
    - uses: actions/checkout@v4

    # Install vcpkg
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        # Bootstrapping vcpkg for Linux
        if [ $RUNNER_OS == 'Linux' ]; then
          ./vcpkg/bootstrap-vcpkg.sh
          echo "${{ github.workspace }}/vcpkg" >> $GITHUB_PATH  # Add vcpkg to PATH
        fi
        # Bootstrapping vcpkg for Windows
        if [ $RUNNER_OS == 'Windows' ]; then
          .\vcpkg\bootstrap-vcpkg.bat
          echo "${{ github.workspace }}\\vcpkg" >> $GITHUB_PATH  # Add vcpkg to PATH
        fi

    # Install dependencies using vcpkg (Linux)
    - name: Install dependencies using vcpkg (Linux)
      if: runner.os == 'Linux'
      run: |
        vcpkg install fltk portaudio

    # Install dependencies using vcpkg (Windows)
    - name: Install dependencies using vcpkg (Windows)
      if: runner.os == 'Windows'
      run: |
        cd ${{ github.workspace }}/vcpkg
        .\vcpkg.bat install fltk portaudio

    # Set reusable strings
    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    # Configure CMake
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
        -S ${{ github.workspace }}

    # Build the project
    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    # Run tests
    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
